import { Header } from "@/components/interface/header";
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "@/providers/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-zinc-900 bg-zinc-100 duration-500 overflow-x-hidden font-poppins">
        <Providers>
          <Header />
          <main className="min-h-screen">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
